### ISSUE TITLE
EEPROM Typo?

### ISSUE THREAD

**Issue by arch-linux** [misterblack1/trs80-diagnosticrom#21]
<img width="870" alt="image" src="https://github.com/user-attachments/assets/9e5122b9-36f4-4fd9-8a0e-7132f0cc5c75">

In the readme.md you wrote "One you have a programmed 2764 or 28B64C"

Did you mean the 28C64B or is this a different EEPROM?

[28C64B](https://ww1.microchip.com/downloads/en/DeviceDoc/doc0270.pdf)

Thank you

**Comment by ki3v** [comment]
Thanks. I think you’re right. I’ll make the correction in the next update.
